backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: 
  - name: "rcy"
    label: "RCY"
    folder: "site/content/rcy" 
    create: true
    slug: "{{title}}" 
    fields: 
      - {label: "Volunteer ID", name: "title", widget: "string"}
      #SECTION-01: PERSONAL DETAILS
      - {label: "Full Name", name: "full_name", widget: "string", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image",
        media_library: 
            config:
                  multiple: true}
      - {label: "Father's Name", name: "fathers_name", widget: "string", required: false}
      - {label: "Mother's Name", name: "mothers_name", widget: "string", required: false}
      - {label: "Permanent Address", name: "perm_add", widget: "string", required: false}
      - {label: "Present Address", name: "present_add", widget: "string", required: false}
      - {label: "Date of Birth", name: "date_of_birth", widget: "date", default: "", format: "DD/MM/YYYY", required: false}
      - {label: "Blood Group", name: "blood_group", widget: "select", options: ["A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-"], required: false}
      - {label: "Gender", name: "gender",  widget: "select", options: ["Male", "Female", "Other"], required: true}
      # SECTION-02: CONTACT INFORMATION & IDENTIFICATION
      - {label: "Email Address", name: "email", widget: "string", requires: false}
      - {label: "Contact Number", name: "contact_no", widget: "number", required: true}
      - {label: "Birth Reg. Certificate No.", name: "birth_cert", widget: "number", required: false}
      - {label: "National ID No.", name: "nid_mo", widget: "number", required: false}
      - {label: "Passport No.", name: "passport_no", widget: "string", required: false}
      # SECTION-03: EMERGENCY CONTACT PERSON
      - {label: "Person Name", name: "emergency_name", widget: "string", required: false}
      - {label: "Relation", name: "emergency_relation", widget: "string", required: false}
      - {label: "Address", name: "emergency_add", widget: "string", required: false}
      - {label: "Contact No.", name: "emergency_contact_no", widget: "number", required: false}
      # SECTION-04: EDUCATION
      - {label: "Name of Institute", name: "edu_inst", widget: "string", required: false}
      - {label: "Subject / Dept", name: "edu_dept", widget: "string", required: false}
      - {label: "Class / Year / Semester", name: "edu_class", widget: "string", required: false}
      - {label: "Roll / ID No.", name: "edu_roll", widget: "string", required: false}

      # # SECTION-05: PARTICIPATION
      - {label: "Trainings Attended", name: "trainings", widget: "list", required: false}
      - {label: "Camps Attended", name: "camps", widget: "list", required: false}
      - {label: "International Visit", name: "int_visit", widget: "list", required: false}
      - {label: "Other Organisation", name: "other_orgs", widget: "list", required: false}
      # # SECTION-00: 
      # - {label: "Trainings Attended", name: "full_name", widget: "string", required: true}
      # - {label: "Trainings Attended", name: "full_name", widget: "string", required: true}
      # - {label: "Trainings Attended", name: "full_name", widget: "string", required: true}
      # - {label: "Trainings Attended", name: "full_name", widget: "string", required: true}
      # - {label: "Trainings Attended", name: "full_name", widget: "string", required: true}
      # - {label: "Trainings Attended", name: "full_name", widget: "string", required: true}
